server:
  port: 8082

spring:
  liquibase:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/acmestore?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate.lob.non_contextual_creation: true
      hibernate.temp.use_jdbc_metadata_defaults: false

openapi:
  server:
    url: http://localhost:8082/

logging:
  level:
    ROOT: DEBUG