springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs

spring:
  application:
    name: acme-store-persist

  liquibase:
    enabled: false
    change-log: classpath:liquibase/master.xml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate.lob.non_contextual_creation: true
      hibernate.temp.use_jdbc_metadata_defaults: false


logging:
  level:
    ROOT: INFO

server:
  port: ${PORT:8082}

openapi:
  title: ACME Persistence Rest API
  version: 1.0.0
  description: API to control operations on the data model.
  server:
    url:
