api:
  integration:
    acme:
      url: http://134.209.29.209/
      key: 76a325g7g2ahs7h4673aa25s47632h5362a4532642
    persist:
      url: http://localhost:8082/acme/store/v1/persist/

logging:
  level:
    ROOT: INFO