server:
  port: ${PORT:8087}

logging:
  level:
    ROOT: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    com.acme.store.job.client.AcmeClient: INFO

store:
  import:
    fixed-delay-milliseconds: ${STORE_IMPORT_DELAY:180000}

api:
  integration:
    acme:
      url: http://134.209.29.209/
      key: 76a325g7g2ahs7h4673aa25s47632h5362a4532642
    persist:
      url: http://localhost:8082/acme/store/v1/persist/

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:acme-store-import}
